apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      containers:
        - name: gateway-service
          image: ankitalodha05/gateway
          ports:
            - containerPort: 3003
          resources:   # ✅ Added Resource Limits
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "250m"
          command: ["node", "app.js"]  # ✅ Adjust if your app requires a specific entrypoint
          args: []  # ✅ Can be left empty or specify arguments if required
